import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <section className="relative flex flex-col h-screen w-full overflow-auto">
            <video
              autoPlay
              muted
              loop
              className="absolute top-0 left-0 min-w-full h-screen z-0 object-fill"
              src="/landing.mp4"
            />
            <div className="absolute top-0 left-0 min-w-full h-screen bg-black opacity-50 z-10"></div>
            <Navbar />
            <div className="relative z-20">{children}</div>
            <Toaster />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
